export const addToCartMeta = {
  name: 'AddToCart',
  label: 'Add to Cart Button',
  description: 'Add-to-cart button with 5 visual styles (primary/secondary/outline/ghost/custom), 3 sizes, hover state, success state, optional preorder indicator. Cart-library-agnostic: takes onAdd(variantId, quantity), isLoading, inStock, isPreorder, preorderAvailableDate. Lucide ShoppingCart/Check/Clock replaced with inline SVG. Theme color resolution via shared resolveColor() if useThemeColors enabled.',
  category: 'product',
  intent: ['cart', 'add-to-cart', 'checkout', 'cta', 'buy'],
  visualRole: 'inline',
  dataDeps: ['selectedVariantId (cart flow)', 'quantity (cart flow)', 'onAdd (injected)'],
  copyFields: ['text', 'preorderText'],
  themeable: ['backgroundColor', 'textColor', 'hoverBackgroundColor', 'hoverTextColor', 'borderColor'],
  a11yRisk: 'low',
  a11yNotes: 'Real <button> with onClick. disabled state reflected via the disabled attribute. Success state is decorative (spans are not announced); the actual cart update comes from consumer cart context which has its own ARIA. Preorder ship date is plain text under the button.',
  mobileBehavior: 'responsive',
  searchTags: ['cart', 'add-to-cart', 'checkout', 'cta', 'buy', 'preorder'],

  props: {
    text: { type: 'string', required: true },
    preorderText: { type: 'string', required: true },
    variant: { type: 'enum', options: ['primary', 'secondary', 'outline', 'ghost', 'custom'], required: true },
    size: { type: 'enum', options: ['sm', 'md', 'lg'], required: true },
    fullWidth: { type: 'boolean', required: true },
    showIcon: { type: 'boolean', required: true },
    disabled: { type: 'boolean', required: true },
    backgroundColor: { type: 'string', required: true },
    textColor: { type: 'string', required: true },
    hoverBackgroundColor: { type: 'string', required: true },
    hoverTextColor: { type: 'string', required: true },
    borderColor: { type: 'string', required: true },
    useThemeColors: { type: 'boolean', required: true },
    marginTop: { type: 'string', required: true },
    marginBottom: { type: 'string', required: true },
    marginLeft: { type: 'string', required: true },
    marginRight: { type: 'string', required: true },
    paddingX: { type: 'string', required: true },
    paddingY: { type: 'string', required: true },
    borderRadius: { type: 'string', required: true },
  },
} as const;

export type AddToCartMeta = typeof addToCartMeta;
