export const imageMeta = {
  name: 'Image',
  label: 'Image',
  description: 'Image with controls for aspect ratio, object fit, width, optional caption (top/bottom), link wrapping, border (color + width), shadow, border radius, hover effect (zoom/brightness/grayscale/lift), and outer alignment + margins. Alt-text is required for accessibility.',
  category: 'content',
  intent: ['image', 'photo', 'picture', 'banner', 'thumbnail'],
  visualRole: 'block',
  dataDeps: [],
  copyFields: ['alt', 'caption'],
  themeable: ['borderColor'],
  a11yRisk: 'high',
  a11yNotes: 'Alt text is mandatory for non-decorative images — set alt to empty string "" explicitly for decorative images (screen readers will skip them). Decorative images are out-of-scope here; the editor should never leave alt blank by default.',
  mobileBehavior: 'responsive',
  searchTags: ['image', 'photo', 'picture', 'src', 'alt', 'img', 'banner', 'thumbnail'],

  props: {
    src: { type: 'string', required: true },
    alt: { type: 'string', required: true },
    aspectRatio: { type: 'enum', options: ['auto', 'square', 'video', 'portrait', 'landscape'] },
    objectFit: { type: 'enum', options: ['contain', 'cover', 'fill', 'none'] },
    width: { type: 'enum', options: ['auto', 'full', 'custom'] },
    customWidth: { type: 'string' },
    showCaption: { type: 'boolean', required: true },
    caption: { type: 'string' },
    captionPosition: { type: 'enum', options: ['top', 'bottom'] },
    captionAlign: { type: 'enum', options: ['left', 'center', 'right'] },
    linkUrl: { type: 'string' },
    openInNewTab: { type: 'boolean', required: true },
    borderRadius: { type: 'enum', options: ['none', 'sm', 'md', 'lg', 'xl', '2xl', 'full'] },
    shadow: { type: 'enum', options: ['none', 'sm', 'md', 'lg', 'xl', '2xl'] },
    showBorder: { type: 'boolean', required: true },
    borderColor: { type: 'string' },
    borderWidth: { type: 'number', required: true },
    hoverEffect: { type: 'enum', options: ['none', 'zoom', 'brightness', 'grayscale', 'lift'] },
    alignment: { type: 'enum', options: ['left', 'center', 'right'] },
    marginTop: { type: 'number', required: true },
    marginBottom: { type: 'number', required: true },
  },
} as const;

export type ImageMeta = typeof imageMeta;
