export const headerMeta = {
  name: 'Header',
  label: 'Header',
  description: 'Site header (top bar + sticky nav + mobile drawer) with layout presets, logo, navigation menu (data injected by consumer via menuItems prop), action icons (search/wishlist/account/cart) with cart badge, and top-bar announcement. Presentational only — accepts pre-fetched menu items as props.',
  category: 'layout',
  intent: ['header', 'navigation', 'nav', 'site-header', 'top-nav', 'menu', 'header-bar'],
  visualRole: 'top',
  dataDeps: ['menuItems (consumer-injected)', 'cartBadgeCount'],
  copyFields: ['logoAlt', 'topBar.leftText', 'topBar.centerText', 'topBar.rightText'],
  themeable: ['backgroundColor', 'textColor', 'menuTextColor', 'menuHoverColor', 'topBar.backgroundColor', 'topBar.textColor'],
  a11yRisk: 'high',
  a11yNotes: 'Landmark element (role=banner on <header>). Keyboard: menu drawer must trap focus and escape must close. Use aria-label on icon-only buttons (already provided via aria-label={action}).',
  mobileBehavior: 'responsive',
  searchTags: ['header', 'nav', 'navigation', 'logo', 'menu', 'cart', 'search', 'drawer', 'mobile-menu'],

  props: {
    layout: { type: 'enum', options: ['left-center-right', 'stacked', 'centered'], required: true },
    backgroundColor: { type: 'string' },
    textColor: { type: 'string' },
    sticky: { type: 'boolean', required: true },
    shadow: { type: 'boolean', required: true },
    transparent: { type: 'boolean', required: true },
    logoPosition: { type: 'enum', options: ['left', 'center', 'right'], required: true },
    logoMaxWidth: { type: 'string', required: true },
    logoUrl: { type: 'string', required: true },
    logoAlt: { type: 'string', required: true },
    menuPosition: { type: 'enum', options: ['left', 'center', 'right'], required: true },
    menuStyle: { type: 'enum', options: ['horizontal', 'vertical'], required: true },
    menuTextColor: { type: 'string' },
    menuHoverColor: { type: 'string' },
    actions: { type: 'array', required: true },
    actionsPosition: { type: 'enum', options: ['left', 'right'], required: true },
    showCartBadge: { type: 'boolean', required: true },
    showLabels: { type: 'boolean', required: true },
    cartBadgeCount: { type: 'number', required: true },
    mobileBreakpoint: { type: 'enum', options: ['sm', 'md', 'lg'], required: true },
    mobileMenuStyle: { type: 'enum', options: ['drawer', 'fullscreen'], required: true },
  },
} as const;

export type HeaderMeta = typeof headerMeta;
