export const testimonialCarouselMeta = {
  name: 'TestimonialCarousel',
  label: 'Testimonial Carousel (Swiper)',
  description: 'Customer-testimonial carousel with card/quote/minimal layout variants, optional avatars and star ratings. Falls back to 5 mock testimonials when items prop is omitted (Puck canvas preview). 5 lucide StarIcon replaced with inline SVG. Uses SwiperBase for shared Swiper config.',
  category: 'swiper',
  intent: ['testimonial', 'review', 'social-proof', 'quote'],
  visualRole: 'block',
  dataDeps: ['items (optional)'],
  copyFields: [],
  themeable: ['backgroundColor', 'cardBackground', 'textColor', 'accentColor'],
  a11yRisk: 'low',
  a11yNotes: 'Avatars have alt text. Star ratings are visual; for screen reader use aria-label on the rating container (e.g. "Rated 5 out of 5"). Consumer can layer that on.',
  mobileBehavior: 'responsive',
  searchTags: ['testimonial', 'review', 'social-proof', 'quote', 'star-rating'],

  props: {
    layout: { type: 'enum', options: ['card', 'quote', 'minimal'], required: true },
    cardsPerView: { type: 'number', required: true },
    cardsPerViewTablet: { type: 'number', required: true },
    cardsPerViewMobile: { type: 'number', required: true },
    effect: { type: 'enum', options: ['slide', 'fade'], required: true },
    showNavigation: { type: 'boolean', required: true },
    navigationColor: { type: 'string', required: true },
    showPagination: { type: 'boolean', required: true },
    paginationType: { type: 'enum', options: ['bullets', 'fraction'], required: true },
    paginationColor: { type: 'string', required: true },
    enableAutoplay: { type: 'boolean', required: true },
    autoplayDelay: { type: 'number', required: true },
    pauseOnHover: { type: 'boolean', required: true },
    loop: { type: 'boolean', required: true },
    spaceBetween: { type: 'number', required: true },
    centeredSlides: { type: 'boolean', required: true },
    showAvatar: { type: 'boolean', required: true },
    showRating: { type: 'boolean', required: true },
    showRole: { type: 'boolean', required: true },
    backgroundColor: { type: 'string', required: true },
    cardBackground: { type: 'string', required: true },
    textColor: { type: 'string', required: true },
    accentColor: { type: 'string', required: true },
    borderRadius: { type: 'enum', options: ['none', 'sm', 'md', 'lg', 'xl', '2xl'], required: true },
    cardShadow: { type: 'enum', options: ['none', 'sm', 'md', 'lg', 'xl'], required: true },
    paddingY: { type: 'number', required: true },
    paddingX: { type: 'number', required: true },
  },
} as const;

export type TestimonialCarouselMeta = typeof testimonialCarouselMeta;
