export const contentSliderMeta = {
  name: 'ContentSlider',
  label: 'Content Slider (Swiper)',
  description: 'Full-bleed content slider for hero banners, promos, and announcements. Each slide has title/description/button/background. Optional custom HTML per slide. Falls back to 3 mock slides. Uses SwiperBase for shared config.',
  category: 'swiper',
  intent: ['hero', 'banner', 'slider', 'carousel', 'announcement'],
  visualRole: 'block',
  dataDeps: [],
  copyFields: ['slides.title', 'slides.description', 'slides.buttonText', 'slides.buttonLink', 'slides.htmlContent'],
  themeable: ['slides.backgroundColor', 'slides.textColor', 'slides.buttonColor', 'overlayColor'],
  a11yRisk: 'medium',
  a11yNotes: 'Swiper has its own a11y for nav buttons. The custom HTML per slide uses dangerouslySetInnerHTML \u2014 the data is editor-controlled, not user-controlled, so trust is OK. Pause-on-hover (autoplay) helps screen-reader users.',
  mobileBehavior: 'responsive',
  searchTags: ['hero', 'banner', 'slider', 'carousel', 'announcement', 'content'],

  props: {
    slides: { type: 'array', required: true, items: '$item' },
    slideHeight: { type: 'enum', options: ['sm', 'md', 'lg', 'xl', 'full'], required: true },
    contentWidth: { type: 'enum', options: ['full', 'contained'], required: true },
    contentPosition: { type: 'enum', options: ['left', 'center', 'right'], required: true },
    effect: { type: 'enum', options: ['slide', 'fade', 'cube', 'coverflow', 'flip'], required: true },
    showNavigation: { type: 'boolean', required: true },
    navigationColor: { type: 'string', required: true },
    navigationPosition: { type: 'enum', options: ['center', 'bottom'], required: true },
    showPagination: { type: 'boolean', required: true },
    paginationType: { type: 'enum', options: ['bullets', 'fraction', 'progressbar'], required: true },
    paginationColor: { type: 'string', required: true },
    enableAutoplay: { type: 'boolean', required: true },
    autoplayDelay: { type: 'number', required: true },
    pauseOnHover: { type: 'boolean', required: true },
    loop: { type: 'boolean', required: true },
    speed: { type: 'number', required: true },
    enableOverlay: { type: 'boolean', required: true },
    overlayColor: { type: 'string', required: true },
    overlayOpacity: { type: 'number', required: true },
  },
} as const;

export type ContentSliderMeta = typeof contentSliderMeta;
