export const featuredProductsMeta = {
  name: 'FeaturedProducts',
  label: 'Featured Products',
  description: 'Section header + product grid (grid or Swiper carousel) with loading/error/empty/success states. Consumer injects products data via prop plus an optional renderProduct callback (D-1 escape hatch) — storefront passes its own <ProductPreview> via the renderProduct prop. Defaults to a simple image+title+price card when renderProduct is omitted.',
  category: 'homepage',
  intent: ['products', 'featured', 'grid', 'carousel', 'hero-products', 'picks'],
  visualRole: 'block',
  dataDeps: ['products (consumer-injected)', 'loading flag', 'error string'],
  copyFields: ['sectionTitle', 'sectionSubtitle', 'buttonText'],
  themeable: ['backgroundColor', 'textColor'],
  a11yRisk: 'medium',
  a11yNotes: 'Carousel uses Swiper with navigation — mouse + keyboard nav supported by default. Pause auto-play on hover/focus for stop-motion users. Img alt text comes from the product card renderer.',
  mobileBehavior: 'responsive',
  searchTags: ['products', 'featured', 'grid', 'carousel', 'hero', 'picks', 'swiper'],

  props: {
    sectionTitle: { type: 'string', required: true },
    sectionSubtitle: { type: 'string' },
    showTitle: { type: 'boolean', required: true },
    displayMode: { type: 'enum', options: ['grid', 'carousel'], required: true },
    productsPerRow: { type: 'number', required: true },
    maxProducts: { type: 'number', required: true },
    slidesPerView: { type: 'number', required: true },
    slidesPerViewTablet: { type: 'number', required: true },
    slidesPerViewMobile: { type: 'number', required: true },
    spaceBetween: { type: 'number', required: true },
    autoplay: { type: 'boolean', required: true },
    autoplayDelay: { type: 'number', required: true },
    loop: { type: 'boolean', required: true },
    navigation: { type: 'boolean', required: true },
    pagination: { type: 'boolean', required: true },
    paginationStyle: { type: 'enum', options: ['dots', 'fraction', 'progressbar'], required: true },
    productSource: { type: 'enum', options: ['featured', 'bestsellers', 'new', 'category', 'manual'], required: true },
    categoryId: { type: 'string', required: true },
    productIds: { type: 'string', required: true },
    backgroundColor: { type: 'string', required: true },
    textColor: { type: 'string', required: true },
    cardStyle: { type: 'enum', options: ['minimal', 'bordered', 'shadow'], required: true },
    showPrice: { type: 'boolean', required: true },
    showAddToCart: { type: 'boolean', required: true },
    buttonText: { type: 'string', required: true },
  },
} as const;

export type FeaturedProductsMeta = typeof featuredProductsMeta;
